### ISSUE TITLE
Not-equals of two lists is not working in `requires:`

### ISSUE THREAD

**Issue by Saviq** [canonical/checkbox#582]
### Bug Description

Given this resource:
```yaml
case: GLMark2Xwayland.fullscreen
xwayland: True
hosted: False

case: GLMark2Xwayland.windowed
xwayland: True
hosted: False

case: HostedGLMark2Wayland.fullscreen
xwayland: False
hosted: True

case: HostedGLMark2Wayland.windowed
xwayland: False
hosted: True
```

And this manifest:
```ini
[manifest]
io.mir-server::skip_xwayland_tests = true
```

With a `==` this correctly skips the cases that don't match.
```plain
requires:
  [manifest.skip_xwayland_tests, "{xwayland}"] == ["True", "True"]

# ...

 ☑ : Run Mir performance test case: GLMark2Xwayland.fullscreen
 ☑ : Run Mir performance test case: GLMark2Xwayland.windowed
 ☐ : Run Mir performance test case: HostedGLMark2Wayland.fullscreen
 ☐ : Run Mir performance test case: HostedGLMark2Wayland.windowed
```

But flip the condition and they all run…

```plain
requires:
  [manifest.skip_xwayland_tests, "{xwayland}"] != ["True", "True"]

# ...

 ☑ : Run Mir performance test case: GLMark2Wayland.fullscreen
 ☑ : Run Mir performance test case: GLMark2Wayland.windowed
 ☑ : Run Mir performance test case: GLMark2Xwayland.fullscreen
 ☑ : Run Mir performance test case: GLMark2Xwayland.windowed
```

Unless I'm missing something weird with requires…

### To Reproduce

See above

### Environment

N/A

**Comment by Saviq** [comment]
Needed to resort to a AND instead:

```yaml
case: GLMark2Wayland.fullscreen
wayland: True
xwayland: False
hosted: False

case: GLMark2Wayland.windowed
wayland: True
xwayland: False
hosted: False

case: GLMark2Xwayland.fullscreen
wayland: False
xwayland: True
hosted: False

case: GLMark2Xwayland.windowed
wayland: False
xwayland: True
hosted: False

case: HostedGLMark2Wayland.fullscreen
wayland: False
xwayland: False
hosted: True

case: HostedGLMark2Wayland.windowed
wayland: False
xwayland: False
hosted: True

case: CompositorPerformance.regression_test_1563287
wayland: True
xwayland: False
hosted: False
```

```yaml
requires:
  [manifest.run_wayland_tests, "{wayland}"] == ["True", "True"] or [manifest.run_xwayland_tests, "{xwayland}"] == ["True", "True"] or [manifest.run_hosted_tests, "{hosted}"] == ["True", "True"]
```
