### ISSUE TITLE
field 'requires', expression did not reference any resources too strict

### ISSUE THREAD

**Issue by Saviq** [canonical/checkbox#746]
### Enhancement Proposal

Say you have a resource:

```yaml
var: foo

var: bar
```

and a templated unit:

```yaml
unit: template
template-resource: foo
id: foo/{var}
requires:
  "{var}" != "bar"
```

This will result in an error:
```
error: units/foo.pxu:5: job 'foo/FUNCTION', field 'requires', expression did not reference any resources
```

So you need to invent an expression to `and` with it. But it's a perfectly valid expression, IMO.
